#+STARTUP: showall indent

* Emacs Utilities

Emacs の shell で動作するユティリティコマンド群です。

** ■ epeco

emacs 上の shell で peco もどきを実現するコマンドです。データの絞り込みに helm を
利用しています。

WSL で peco を利用するには Windows 10 April 2018 Update 以降が必要なようですが、
本コマンドにはこの制限はありません。

emacs が emacsclient と通信できるようになっており、helm が設定されていれば利用
可能です。同期バージョンと非同期バージョンがあり、それぞれ以下の特徴があります。

|--------------+----------+------------------------------------------------------------|
| コマンド名称 | 動作種別 | 特徴                                                       |
|--------------+----------+------------------------------------------------------------|
| epeco-async  | 非同期   | ・入力するデータを全て取り込む前にコマンドが起動します     |
| 　　〃       | 　〃     | ・migemo は使えません                                      |
| 　　〃       | 　〃     | ・emacs を起動しているホストでのみ利用できます             |
|--------------+----------+------------------------------------------------------------|
| epeco-sync   | 同期     | ・入力するデータを全て取り込んでからコマンドが起動します   |
| 　　〃       | 　〃     | ・migemo が使えます（要 cmigemo）                          |
| 　　〃       | 　〃     | ・tramp で接続した先でも利用できます（emacsclient は必要） |
|--------------+----------+------------------------------------------------------------|

使うコマンドを epeco という名称でシンボリックリンクしてお使いください。

*** 使用方法

#+BEGIN_EXAMPLE
epeco [-q query] [file]
epeco -h
#+END_EXAMPLE

*** コマンドオプション

**** ● -q query オプション

絞り込み文字列の初期値を設定するオプションです。

*** tramp の接続先から利用する場合の設定

tramp の接続先から epeco-sync や以降で紹介する einp を使う場合は、以下の設定を行ってください。

１）emacs を起動しているホストの ~/.ssh/config に以下のような設定を行う

#+BEGIN_EXAMPLE
Host <aliasname>
     HostName       <hostname>
     Port           <portno>    # 必要であれば
     User           <username>
     RemoteForward  /tmp/server /tmp/emacs1000/server # 1000 の数字は、id -u の値に置き換える
#+END_EXAMPLE

※ OpenSSH 6.7 でサポートされた Unix domain socket forwarding の機能を使っています
- https://www.openssh.com/txt/release-6.7

２）tramp の接続先の ~/.bashrc に以下の設定を行う

#+BEGIN_EXAMPLE
if [ -S /tmp/server ]; then
    mkdir -p /tmp/emacs$(id -u)
    mv /tmp/server /tmp/emacs$(id -u)
fi
#+END_EXAMPLE

３）以下のコマンドを発行してコネクションをクリアしてから、<aliasname> に tramp で再接続し、
M-x shell で shell を起動する

#+BEGIN_EXAMPLE
M-x tramp-cleanup-all-connections
#+END_EXAMPLE

４）コマンドパスの通ったディレクトリ（~/bin 等）に epeco-sync と einp（以降で説明）を複写し、
以下のコマンドにより、epeco コマンドを利用できるようにする

#+BEGIN_EXAMPLE
cd ~/bin
ln -s epeco-sync epeco
#+END_EXAMPLE

５）以降の使用例を参考に、コマンドを利用する

注）接続先への ssh 接続は、tramp を介して行うようにしてください。（dired でリモートホストを
開き、そこで M-x shell を実行する。）ローカルホストで起動した shell から ssh コマンドで
リモートホストに接続しても、本コマンドは利用できません。また、ssh コマンドでリモートホスト
に接続してしまった場合は、３）を再実行してください。

*** 使用例

#+BEGIN_EXAMPLE
sleep 1000 & sleep 2000 & sleep 3000 &
ps -ef | epeco | awk '{print $2}'
ps -ef | epeco | awk '{print $2}' | xargs -r kill

find * -type d -name '.*' -prune -o -type d -print | epeco
find * -type d -name '.*' -prune -o -type d -print | epeco | xargs -i emacsclient -n {}

history | tac | epeco | cut -b8-
eval "$(history | tac | epeco | cut -b8-)" # xargs を使うと、cd などが上手く実行できない

docker ps -a | epeco | awk '{print $1}'
docker ps -a | epeco | awk '{print $1}' | xargs -r docker rm

docker images | epeco | awk '{print $3}'
docker images | epeco | awk '{print $3}' | xargs -r docker rmi
#+END_EXAMPLE

helm は M-a で全選択が機能しますので、候補を絞った後に利用すると便利です。

*** 注意事項

**** ● shell-mode の shell で動かすことを前提としたコマンドです

epeco-sync は ansi-term など shell-mode 以外の shell では動作しません。
epeco-async は shell-mode 以外の shell でも動作しますが、以降で紹介する einp と組み合わせて
利用する場合、shell-mode の shell が必要となります。

*** 参考情報

helm の source の設定方法については、以下を参照してください。

- https://github.com/emacs-helm/helm/wiki/Developing

*** 関連情報

外部端末で peco を動かすラッパーが以下で紹介されています。emacs の環境下で peco
そのものを使いたい場合は、こちらの利用を検討ください。

- http://emacs.rubikitch.com/peco-wrapper/

emacs でコマンドヒストリを使う方法としては以下の方法もあります。tramp の接続先でも
動作しますし、接続先に emacsclient が必要なく、tramp の接続であれば ssh の接続に
限らない（docker-tramp.el による docker exec の接続でも利用可能）などのメリットも
あります。こちらの利用も検討ください。

- https://www49.atwiki.jp/ntemacs/pages/35.html
- https://qiita.com/kai2nenobu/items/7af012e327b8dd078ba4

** ■ einp

emacs 上の shell-mode で動作する、コマンド入力を支援するコマンドです。コマンドが標準入力で
受け付けた文字列を次に実行するコマンドとして登録します。

epeco と組み合わせて利用することを想定して作成しました。emacs が emacsclient と通信できる
ようになっていれば利用可能です。

*** 使用方法

#+BEGIN_EXAMPLE
einp [-s]
einp -h
#+END_EXAMPLE

*** コマンドオプション

**** ● -s オプション

標準入力から受け付けた文字列が複数行の場合、一行のコマンドに変換して登録します。

*** 使用例

#+BEGIN_EXAMPLE
echo ls | einp

echo -e "ls\nls"
echo -e "ls\nls" | einp
echo -e "ls\nls" | einp -s

sleep 1000 & sleep 2000 & sleep 3000 &
ps -ef | epeco | awk '{print $2}' | xargs -r echo kill
ps -ef | epeco | awk '{print $2}' | xargs -r echo kill | einp

history | tac | epeco | cut -b8-
history | tac | epeco | cut -b8- | einp
history | tac | epeco | cut -b8- | einp -s

docker ps -a | epeco | awk '{print $1}' | xargs -r echo docker rm
docker ps -a | epeco | awk '{print $1}' | xargs -r echo docker rm | einp

docker images | epeco | awk '{print $3}' | xargs -r echo docker rmi
docker images | epeco | awk '{print $3}' | xargs -r echo docker rmi | einp
#+END_EXAMPLE

よく使うコマンドを alias 設定しておくのが良いと思います。

#+BEGIN_EXAMPLE
alias ek="ps -ef | epeco | awk '{print \$2}' | xargs -r echo kill | einp"
alias eh="history | tac | epeco | cut -b8- | einp -s"
alias edp="docker ps -a | epeco | awk '{print \$1}' | xargs -r echo docker rm | einp"
alias edi="docker images | epeco | awk '{print \$3}' | xargs -r echo docker rmi | einp"
#+END_EXAMPLE

helm は M-a で全選択が機能しますので、候補を絞った後に利用すると便利です。

*** 注意事項

**** ● shell-mode 以外の shell では動作しません

ansi-term など shell-mode 以外の shell では動作しません。
